Update dependencies for MVO
openshift/managed-velero-operator pull request #90
Opened 2020-10-07 19:10 UTC by cblecker

2020-10-07 23:22 UTC, cblecker commented
/hold
for review

2020-10-08 12:36 UTC, yithian requested changes
version updates all seem fine, i'd like to see a unit test for `generateServiceMonitor(...)` though

2020-10-08 12:36 UTC, yithian commented on pkg/controller/velero/velero.go
> +func generateServiceMonitor(s *corev1.Service) *monitoringv1.ServiceMonitor {
if this is a function that we're going to own then we should have a unit test for it imo

2020-10-08 16:46 UTC, mbarnes commented
/lgtm

2020-10-08 16:50 UTC, yithian approved these changes

2020-10-08 16:51 UTC, cblecker commented
/hold cancel

2020-10-08 16:56 UTC, merged